name: Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{github.workspace}}
      - name: Check out repository code
        uses: actions/checkout@v4

